### ISSUE TITLE
Bug in Rouchon2

### ISSUE THREAD

**Issue by gautierronan** [dynamiqs/dynamiqs#190]
> It's a little weird that the `Rouchon2` performs bad no? 🤔

Yes I think there's a bug. By reducing to `dt = 1e-4` I get a worse performance than `dt = 1e-3`. I'm pretty sure it used to work so probably a bug introduced in a recent PR? Rouchon1 seems correct though because reducing `dt` by a factor of 10, I get a factor 10 reduction in error as well.

_Originally posted by @gautierronan in https://github.com/dynamiqs/dynamiqs/issues/166#issuecomment-1661740529_

**Comment by gautierronan** [comment]
In the end, I think it works as intended. Probably we're hitting some other limit (machine precision?) when reducing `dt` to `dt=1e-4`. Closing this for now, feel free to re-open.

**Comment by pierreguilmin** [comment]
It's a bit too large for machine précision issue, I think we should investigate this further. If the scheme is not bugged, we should document this limit once we understand why it exists.

**Comment by gautierronan** [comment]
> It's a bit too large for a machine precision issue, and I guess you'll have the same in double precision. I think we should investigate this further. If the scheme is not bugged, we should document this limit once we understand why it exists.

But reducing from `dt=1e-2` to `dt=1e-3`, I do get a 10^2-fold reduction in error, as expected from an order 2 scheme. So there's something else we're hitting.

**Comment by gautierronan** [comment]
Below is the actual plot of the error against `dt` for the test problem we have. The dashed black line shows `y = 10 * dt**2`. I'm not sure what's happening at short times and the sudden drop in error at `t=0.5`, but otherwise I'd call that a working solver. And we might actually be hitting machine precision at `1e-6` error in the norm. Note that the machine precision error can build up throughout the solver and scale with the matrix size when taking the norm.

![rouchon2_error](https://github.com/dynamiqs/dynamiqs/assets/25346881/4ca0df71-5b32-41ea-9e3d-7ecd31ba12a2)

**Comment by pierreguilmin** [comment]
Nice plot! I'm convinced now. I'd love to see if we can go lower for double precision, but it's not worth the trouble if you don't have time. Thanks for the detailed analysis.
