### ISSUE TITLE
implement a ver() method

### ISSUE THREAD

**Issue by blaise-vignon** [dynamiqs/dynamiqs#195]
As a user if I want to make sure my setup is up to date with the latest version, I want to be able to call dq.ver() to know which version I am running

**Comment by pierreguilmin** [comment]
Thanks for the suggestion, we definitely need this! Using `package.__version__` is quasi-standard to get the installed version of a Python package, so it's probably the best way to go. I'll work on this.

**Comment by pierreguilmin** [comment]
Meanwhile you can always drop a `pip list | grep dynamiqs` in your terminal 😉
