### ISSUE TITLE
Implement custom `sqrtm` for `dm_fidelity`

### ISSUE THREAD

**Issue by gautierronan** [dynamiqs/dynamiqs#237]
See https://arxiv.org/pdf/2201.08663.pdf and https://github.com/KingJamesSong/FastDifferentiableMatSqrt/blob/main/torch_utils.py for the implementation.

This or a Newton method should be more stable and faster than svd/eigh-based implementations.

**Comment by pierreguilmin** [comment]
We closed #243 because the fidelity is ~1%, which is too low.

**Comment by pierreguilmin** [comment]
See https://linear.app/dynamiqs/issue/DYN-87/implement-custom-sqrtm-for-dm-fidelity.
