### ISSUE TITLE
Steadystate solvers

### ISSUE THREAD

**Issue by abocquet** [dynamiqs/dynamiqs#240]
Useful but currenlty missing feature from the library. The solvers we want to implement have to be discussed

https://qutip.org/docs/4.0.2/guide/guide-steady.html

**Comment by pierreguilmin** [comment]
Yes this is really a needed feature!

**Comment by pierreguilmin** [comment]
See https://linear.app/dynamiqs/issue/DYN-38/add-steadystate-solver.
