### ISSUE TITLE
Document damped driven qubit tests calculations

### ISSUE THREAD

**Issue by abocquet** [dynamiqs/dynamiqs#326]
Defined in https://github.com/dynamiqs/dynamiqs/pull/276 and needs math background as explained in https://github.com/dynamiqs/dynamiqs/pull/322/files#diff-dacac2ebf9792f0d23c0f922a744486ded01901957d5281290925acd89cf83acR1

@pierreguilmin and I have everything ready, just need to write it down, let's wait for https://github.com/dynamiqs/dynamiqs/pull/322 to be merged to do it

**Comment by pierreguilmin** [comment]
Do you mean document in the website?

**Comment by pierreguilmin** [comment]
Ho, I think you meant this, I changed the title.
