### ISSUE TITLE
Write a coding style guide

### ISSUE THREAD

**Issue by abocquet** [dynamiqs/dynamiqs#342]
Write down all conventional rules we want to agree on
- use types instead of typing helpers (`Tuple` -> `tuple`)
- only simple quotes 
- ... ?

**Comment by pierreguilmin** [comment]
Thank you for that 😍 I have tracked most of them in a dirty note, I'll tidy it up.

**Comment by abocquet** [comment]
In our discussions, let's refrain from relying solely on subjective arguments, as their value lies solely in the opinions of the individuals expressing them. General statements such as "I don't like it," "it's odd," or "it's simpler" lack the specificity needed to advance the debate. Instead, let's articulate our concerns by providing concrete reasons:

- "I don't like it because [it's slow/lengthy/error-prone/...]"
- "It's odd because in X/Y library, they follow a different approach."
- "It's simpler" ➡️ "It will prevent errors" / "It requires fewer steps."

By identifying specific points of concern, we can effectively address and evaluate them, either leading to the modification or abandonment of proposed solutions based on well-founded reasons. This approach will enable us to make informed decisions and make progress in our discussions.

**Comment by pierreguilmin** [comment]
See https://linear.app/dynamiqs/issue/DYN-86/write-a-coding-style-guide.
