### ISSUE TITLE
Stopping dq.mesolve bugs Jupyter interface

### ISSUE THREAD

**Issue by rdelavie** [dynamiqs/dynamiqs#392]
If dq.mesolve computation is stopped (either because of an error, timeout or user action),
when it is launched again, the progress bar does not remain on its line. We have to reboot the kernel every time.

![image](https://github.com/dynamiqs/dynamiqs/assets/146200418/fb3cd022-c9b0-44c4-80eb-8926207f2aa2)

Thanks,

**Comment by rdelavie** [comment]
Environment: Ubuntu VM, Jupyter Notebook

**Comment by pierreguilmin** [comment]
Hi @rdelavie, thanks for reporting the issue! I think we do not properly close the progress bar when the integration is interrupted. We should enclose our main solver loop in a try-finally block to ensure that the progress bar is always closed. Let me open a PR.
