### ISSUE TITLE
Wigner function with arbitrary xvec, yvec

### ISSUE THREAD

**Issue by HarshBabla99** [dynamiqs/dynamiqs#528]
Hello, 
Firstly, thanks so much for creating this wonderful package and making it available for everyone. It is so well written and a pleasure to use!
Could you consider a slight edit to the `dq.wigner(...)` method? Currently the method takes in two values `xmax` & `ymax`, and creates a symmetric wigner function - extending equally far vertically and horizontally. Would you be okay with allowing for arbitrary `xvec` and `yvec` values as inputs to the method? Going through the source code, it should be a straightforward change. 

Here are a few reasons to motivate the change:
1. **Generality**: It's nice to have more flexibility and plot Wigner functions for arbitrary regions in phase space. This is especially useful for zooming into interesting regions. 
2. **Backwards compatibility with QuTiP** 
3. **Getting the Wigner values for specific values**: For many Bosonic codes key properties such as the expectation values of Pauli operators eg. $\langle X \rangle$, $\langle Z \rangle$, $\langle XX \rangle$, etc. can be minimally extracted by evaluating the Wigner function at specific displacements in phase space. (See: Pg 7 onwards in the Appendix of [https://arxiv.org/pdf/2311.04423.pdf](url)). This would be very inconvenient to do with the current dynamiqs' implementation. 

Of course, all these problems would be solved if one directly calls `_wigner_clenshaw()` or `_wigner_fft`. But this is quite a clumsy hack, and it is perhaps unsavory to use private methods. Moreover, the nice jit and auto-vec optimization that you have implemented on the wrapper would be lost. 

I hope you consider implementing this change. If you decide to implement it, I would be happy to contribute.

**Comment by pierreguilmin** [comment]
Relates to https://linear.app/dynamiqs/issue/DYN-150/change-wigner-parameters-from-scalars-to-tensors.

**Comment by abocquet** [comment]
Hello @HarshBabla99 
I had the code around so I pushed to #529. Can you test the branch `abocquet/wigner-arbitrary` and tell me if this is what you had in mind?

**Comment by pierreguilmin** [comment]
> Getting the Wigner values for specific values: For many Bosonic codes key properties such as the expectation values of Pauli operators eg. $\braket{X}$, $\braket{Z}$, $\braket{ZZ}$, etc. can be minimally extracted by evaluating the Wigner function at specific displacements in phase space. (See: Pg 7 onwards in the Appendix of https://arxiv.org/pdf/2311.04423.pdf). This would be very inconvenient to do with the current dynamiqs' implementation.

@HarshBabla99 regarding this comment, I think the best way to evaluate these quantities is to compose existing functions rather than using `dq.wigner()`.  It's actually quite straightforward because all functions are batch-compatible. For example to evaluate the value of the Wigner function for a few specific displacements:
```python
import jax
import dynamiqs as dq

n = 8

# create a random density matrix
key = jax.random.PRNGKey(42)
rho = dq.rand_dm(key, (n, n))

# compute the wigner function at various positions
alphas = [0.0, 1, 1j]
D = dq.displace(n, alphas)
dq.expect(dq.parity(n), D @ rho @ dq.dag(D))
# Array([-0.11009671,  0.02406528, -0.07013579], dtype=float32)
```

**Comment by pierreguilmin** [comment]
@HarshBabla99 we've merged the fix (along with some other improvements to the wigner function). New API here > https://www.dynamiqs.org/python_api/utils/utils/wigner.html, hope this meets your needs.

**Comment by HarshBabla99** [comment]
Hi Pierre and Adrien,

Sorry for not replying back sooner. 
But, thanks so much for implementing the change. 
I just tested it out and it works great! Thanks!
