### ISSUE TITLE
Allow Hamiltonian arguments to be multidimensional without batching

### ISSUE THREAD

**Issue by dkweiss31** [dynamiqs/dynamiqs#547]
I'd like for some of the arguments I pass to my Hamiltonian functions to be multidimensional. A simple example is the following where I have multiple drive Hamiltonians and want to specify the amplitudes as an array.

```python
import dynamiqs as dq
import jax.numpy as jnp
from dynamiqs import timecallable
from dynamiqs.solver import Tsit5

omega = 2.0 * jnp.pi * 1.0
H0 = -0.5 * omega * dq.sigmaz()
H1s = [dq.sigmax(), dq.sigmay()]

def H_func(t, amps):
    H = H0 + jnp.einsum("i,ijk->jk", jnp.cos(omega * t) * amps, H1s)
    return H

H_tc = timecallable(H_func, args=(jnp.array([0.01, 0.02]),))
tsave = jnp.linspace(0, 1.0, 21)
initial_states = [dq.basis(2, 1), ]
result = dq.sesolve(
    H_tc,
    initial_states,
    tsave,
    solver=Tsit5(),
)

``` 
This code raises an error `ValueError: Einstein sum subscript 'i' does not contain the correct number of indices for operand 0.
` as the code attempts to batch over `amps` which is not my intent. Of course I could just pass them in as individual arguments `amp_x` and `amp_y` but I have more complex examples in mind where this wouldn't work as easily. I'm wondering if there is an alternative to checking argument dimensions for batching? Might it make more sense to make it similar to how batching over e.g. initial states works, and stack `timecallable` instances?

**Comment by pierreguilmin** [comment]
Hey @dkweiss31! Your question is timely, this is an issue we are aware of and we are in the middle of a big brainstorming in the core team to propose a better refactor of the `TimeArray` API to support batching/non-batching in a simpler way. Thanks for giving us another use case, it's very helpful. 🙏 We'll keep you updated on the solution 😉

**Comment by gautierronan** [comment]
In the meantime, I guess a simple solution would be not pass `amps` as an input to your function, e.g.

```python
amps = jnp.array([0.01, 0.02])

def H_func(t):
    H = H0 + jnp.einsum("i,ijk->jk", jnp.cos(omega * t) * amps, H1s)
    return H

H_tc = timecallable(H_func)
```
Or alternatively with a `functools.partial`,
```python
from functools import partial

def H_func(t, *, amps):
    H = H0 + jnp.einsum("i,ijk->jk", jnp.cos(omega * t) * amps, H1s)
    return H

amps = jnp.array([0.01, 0.02])
H_tc = timecallable(partial(H_func, amps=amps))
```

**Comment by dkweiss31** [comment]
@pierreguilmin gotcha sounds great! Looking forward to seeing your solution :) 

@gautierronan thanks for the suggestions! I should have been more specific about my use case. I'm trying to do GRAPE and have e.g. a 3x11 array I'm optimizing over: three drives and each has 11 knot points that I fit a spline to to make the drives continuous in time. So I'm not positive those solutions would work in that context. My ugly solution now without reverting back to earlier versions is to just hard code 
```python
is_batched = (
        False, #is_timearray_batched(H),
        psi0.ndim > 2,
        False,
        False,
        False,
        False,
        False,
    )
``` 
to prevent it trying to batch over the 3x11 array.

**Comment by gautierronan** [comment]
I think that should be possible nonetheless with the current API. If you want to differentiate against `amps` but not batch, you can write it like so (with a dummy cost function):
```python
import dynamiqs as dq
import jax.numpy as jnp
import jax
from functools import partial

omega = 2.0 * jnp.pi * 1.0
H0 = -0.5 * omega * dq.sigmaz()
H1s = [dq.sigmax(), dq.sigmay()]
tsave = jnp.linspace(0, 1.0, 21)
psi0 = dq.basis(2, 1)

def f(t, *, amps):
    H = H0 + jnp.einsum("i,ijk->jk", jnp.cos(omega * t) * amps, H1s)
    return H
    
def cost_function(amps):
    H = dq.timecallable(partial(f, amps=amps))
    result = dq.sesolve(H, psi0, tsave)
    return dq.expect(dq.sigmaz(), result.states[-1]).real

amps = jnp.array([0.01, 0.02])
print(jax.grad(cost_function)(amps))
# [0.00999917 0.01999832]
```

**Comment by dkweiss31** [comment]
Nice that does work, thank you! I'm wondering if its possible to combine that approach with another argument that you do batch over? I've made a few attempts all of which failed. Maybe this is something where I should simply be patient and wait or the new API lol

**Comment by gautierronan** [comment]
Here is how you can also batch over `omega`, as an example:
```python
import dynamiqs as dq
import jax.numpy as jnp
import jax
from functools import partial

omegas = jnp.array([2.0 * jnp.pi, 4.0 * jnp.pi])
H0 = -0.5 * dq.sigmaz()
H1s = [dq.sigmax(), dq.sigmay()]
tsave = jnp.linspace(0, 1.0, 21)
psi0 = dq.basis(2, 1)

def _H(t, omega, *, amps):
    return omega * H0 + jnp.einsum("i,ijk->jk", jnp.cos(omega * t) * amps, H1s)

def cost_function(amps):
    H = dq.timecallable(partial(_H, amps=amps), args=(omegas,))
    result = dq.sesolve(H, psi0, tsave)
    return dq.expect(dq.sigmaz(), result.states[0, -1]).real

amps = jnp.array([0.01, 0.02])
print(jax.grad(cost_function)(amps))
# [0.00999917 0.01999832]
```

**Comment by dkweiss31** [comment]
Nice that's exactly what I was looking for, thank you @gautierronan :)

**Comment by gautierronan** [comment]
Indeed it comes from the fact that `omega` and `H0`/`H1` are not broadcastable, my bad. Here's an implementation that works, and actually avoids the trick with the partial (although that should still work if needed):
```python
import jax
import jax.numpy as jnp
import dynamiqs as dq

omegas = jnp.array([2.0 * jnp.pi, 4.0 * jnp.pi, 6.0 * jnp.pi])
H0 = -0.5 * dq.sigmaz()
H1s = [dq.sigmax(), dq.sigmay()]
tsave = jnp.linspace(0, 1.0, 21)
psi0 = dq.basis(2, 1)

def cost_function(amps):
    Hc = jnp.einsum("i,ijk->jk", amps, H1s)

    def _H(t, omega):
        omega = omega[..., None, None]
        return omega * H0 + jnp.cos(omega * t) * Hc

    H = dq.timecallable(_H, args=(omegas,))
    result = dq.sesolve(H, psi0, tsave)
    return dq.expect(dq.sigmaz(), result.states[0, -1]).real

amps = jnp.array([0.01, 0.02])
print(jax.grad(cost_function)(amps))
# [0.00999917 0.01999832]
```
Notice the call `omega = omega[..., None, None]` which is the real trick here. That's the kind of thing we're trying to make clearer and more systematic with the TimeArray API we're working on.

**Comment by pierreguilmin** [comment]
Hey @dkweiss31! Sorry, making the new API neat and clean required quite some work, but you can check this page > https://www.dynamiqs.org/tutorials/time-dependent-operators.html#modulated-operators to know more about the new batching for your use case. Tell us if that works for you 😉
