### ISSUE TITLE
DIA sparse matrix product

### ISSUE THREAD

**Issue by gautierronan** [dynamiqs/dynamiqs#62]
Implementing a homemade DIA sparse-dense matrix product would be nice at some point.

Below is a small benchmark showing how much we can gain, even from a poorly written spmm, for a simple `a @ rho @ a.adjoint()` multiplication.

<details>
  <summary>Benchmarking code</summary>

```python
import torch
import torch.utils.benchmark as benchmark

N = 100
dtype = torch.complex64
device = torch.device("cuda:0")

# Kraus operator
D = torch.sqrt(torch.arange(1, N)).to(dtype=dtype, device=device)
A = torch.diag(torch.sqrt(torch.arange(1, N)), 1).to(dtype=dtype, device=device)

# Initial state
rho = torch.randn(N, N, dtype=dtype, device=device)
rho = rho + rho.adjoint()

# Kraus map functions
@torch.jit.script
def krausmap(A, rho):
    return torch.einsum("ij,jk,kl->il", A, rho, A.adjoint())

@torch.jit.script
def krausmap_custom(D, rho):
    tmp = torch.zeros_like(rho)
    tmp[:-1, :-1] = D[:, None] * D[None, :] * rho[1:, 1:]
    return tmp


# Test functions work
assert torch.norm(krausmap_custom(D, rho) - krausmap(A, rho)) < 1e-2

# Benchmark
mul = "krausmap(A, rho)"
mul_custom = "krausmap_custom(D, rho)"

t = benchmark.Timer(
    stmt=mul,
    setup="from __main__ import krausmap",
    globals={"A": A, "rho": rho}
)
t_custom = benchmark.Timer(
    stmt=mul_custom,
    setup="from __main__ import krausmap_custom",
    globals={"D": D, "rho": rho},
)

print(t.timeit(100))
print(t_custom.timeit(100))
```
</details>

which yields the following results

| Size | einsum | custom | Speedup |
| --- | --- | --- | --- |
| N = 10 (cpu)| 64.09 us | 18.61 us | x3.44 |
| N = 100 (cpu) | 243.88 us | 28.45 us | x8.57 |
| N = 1000 (cpu) | 167.50 ms | 2.28 ms | x73.5 |
| |
| N = 10 (gpu)| 70.65 us | 37.93 us | x1.86 |
| N = 100 (gpu) | 62.76 us | 38.06 us | x1.65 |
| N = 1000 (gpu) | 1.02 ms | 93.76 us | x10.9 |

**Comment by PierreGuilmin** [comment]
I think we should compare to torch sparse directly no?

**Comment by abocquet** [comment]
I have a semi-implementation of the "generalized" sparse matrix. Here is some benchmark to add some "water to the moulin". Performances are very bad (although asymptotically better) but I'm working on it﻿ ﻿
![SCR-20230405-l5n](https://user-images.githubusercontent.com/4300678/230091365-3d92750b-b8f4-4f5c-8343-e56a1378298b.png)

**Comment by gautierronan** [comment]
> I think we should compare to torch sparse directly no?

I did it as well but didn't show the results. The torch sparse COO format is overall faster than dense, and ~2 times slower than my custom DIA. But it doesn't have many operations with autograd support, so I don't think we can use it for the package yet. Maybe in some time when Torch develops it some more.

Although to be fair, my poorly written DIA is fast just because I'm only looking at sparse matrix with a single diagonal. If I have more than this, it's really not as good.

> I have a semi-implementation of the "generalized" sparse matrix. Here is some benchmark to add some "water to the moulin". Performances are very bad (although asymptotically better) but I'm working on it﻿ ﻿

That's really cool ! What are you doing in "Sparse without conversion" ? Is this all kernel code?

**Comment by pierreguilmin** [comment]
See https://linear.app/dynamiqs/issue/DYN-48/support-sparse-dia-format.
