### ISSUE TITLE
Input experimental data in stochastic solver

### ISSUE THREAD

**Issue by BenjaminDAnjou** [dynamiqs/dynamiqs#747]
I was looking over the early documentation for the stochastic solver `smesolve()` in `dynamiqs`.

It occurred to me that it doesn’t seem to include the explicit capability of inputing experimental data into the solver. It's usually possible to break stochastic solvers in two parts: a function that generates data, and then a function that filters the density matrix over this data.

If you want to use the SME to do parameter estimation, for instance, you often have to solve the SME with different dynamical parameters but on the same fixed dataset (generated by the true parameters).

In my (humble) experience, this also makes the solver closer in spirit to quantum measurement theory and thus makes it more easily generalizable to other types of measurements (you can reuse many core functions).

Do you think that would be a good feature to implement, even if just in the backend for now? I'm sure there would be some technical issues, but I think it would be a useful feature in practice. Let me know what you think. I doubt I would have the time to work on this in the near future, but I'll consider it if there is interest.

**Comment by pierreguilmin** [comment]
Hi @BenjaminDAnjou, thank you for raising this question. 😊 We are not planning to include this feature in Dynamiqs, for two main reasons:

- Although mathematically similar, the way we handle Wiener processes in Dynamiqs -- based on virtual Brownian trees, the method used by Diffrax -- does not easily allow for a unified solver (e.g. with the support for adaptive step-sizing and checkpointing algorithms to compute gradients).
- We are focusing on implementing a few general solvers in Dynamiqs, to ensure good code quality and ease of maintenance in the long term.  Reconstructing the state from experimental continuous measurement data is (arguably) a bit more _niche_ than what we plan to support.

As a side note, using a digitized signal to reconstruct the state from the SME is only valid up to a fixed order in the digitization time $\Delta t$, regardless of the solver used. This contrasts with the type of solvers we implement, which can, in principle, be arbitrarily precise.

That being said, I agree that having well-written open-source code for this would be useful. If you're interested, it would be great to have it another library on top of Dynamiqs, such as [qontrol](https://github.com/dkweiss31/qontrol).

**Comment by pierreguilmin** [comment]
I'm closing this for now, but I'm happy to reconsider it if it becomes necessary for many people.

**Comment by BenjaminDAnjou** [comment]
Thanks for your reply! As long as you thought about it and decided that it was a bad idea for this library, it's good enough for me. I will have a look at `qontrol`.
