### ISSUE TITLE
Dynamiqs does not properly credit QuTiP per the BSD-3 license

### ISSUE THREAD

**Issue by nonhermitian** [dynamiqs/dynamiqs#799]
Portions of your code are based on QuTiP code, e.g .https://github.com/dynamiqs/dynamiqs/blob/7fc017ddc84357e005e1907ccb811d585db45153/dynamiqs/utils/quantum_utils/wigner.py#L66, but do not properly give attribution under the BSD-3 license governing QuTiPs source.

In particular part one of the license is applicable here:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

**Comment by gautierronan** [comment]
Hi @nonhermitian, thanks for pointing this out. It's fixed in https://github.com/dynamiqs/dynamiqs/pull/800 by adding the BSD-3 license from QuTiP.

**Comment by hodgestar** [comment]
@gautierronan Thanks for adding the license so speedily and thank you @nonhermitian for pointing out the omission.
